branch-defaults:
  master:
    environment: buahtanganBackend-dev
    group_suffix: null
global:
  application_name: buahtanganBackend
  branch: null
  default_ec2_keyname: buahtangan
  default_platform: Node.js
  default_region: ap-southeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
